name: navigation
description: "Navigation module"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: 
  splash: 
    path: ../features/splash/
  welcome: 
    path: ../features/welcome/
  login:
    path: ../features/login/
  register: 
    path: ../features/register/
  home: 
    path: ../features/home/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

