name: register
description: "Register screen"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  core_ui: 
    path: ../../core_ui
  flutter_svg: ^2.0.10+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.7.0
  build_runner: ^2.4.12

flutter_gen:
  output: lib/util/

flutter: 
  assets:
    - assets/images/svg/lock.svg
    - assets/images/svg/user.svg
    - assets/images/svg/mail.svg