name: error
description: "error page"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_ui: 
    path: ../../core_ui
  core: 
    path: ../../core
  navigation:  
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen:  
  build_runner: 

flutter_gen:
  output: lib/util/

