name: splash
description: "Splash page"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.13
  core_ui: 
    path: ../../core_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.7.0
  build_runner: ^2.4.12

flutter_gen:
  output: lib/util/assets/

flutter:
  assets: 
    - assets/images/
    - assets/rive/