name: core_ui
description: "Common ui core"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  splash:
    path: ../features/splash
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen:
  build_runner:

flutter_gen: lib/codegen

flutter:
  uses-material-design: true
  fonts:
    - family: 'Minecraft'
      fonts:
        - asset: assets/fonts/minecraft.ttf